services:   

  frontend:
    container_name: frontend
    build: ./team037-frontend/grocery-express
    restart: always
    ports:
      - 4201:4200
    depends_on:
      - grocery

  grocery:
    container_name: grocery
    #image: grocery
    build: ./cs6310_fa21_team037
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - redis
      - mysql
    command: >
      sh -c "sleep 5 &&
         java -jar app.jar"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  mysql:
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cs6310_fa21_team037
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    image: mysql
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE